ifeq (eabi,$(findstring eabi,$(TARGET)))

CC ?= $(TARGET)-gcc
AR ?= $(TARGET)-ar

CONFIGURE_FLAGS := --host=$(TARGET)
CFLAGS := -fPIC

SRC_DIR = $(shell pwd)

.PHONY: all
all:
	cd $(OUT_DIR) && $(SRC_DIR)/expat/configure $(CONFIGURE_FLAGS) CFLAGS=$(CFLAGS)
	cd $(OUT_DIR) && make -j$(NUM_JOBS)
	cp $(OUT_DIR)/.libs/libexpat.a $(OUT_DIR)
	mkdir -p $(OUT_DIR)/include
	cp expat/lib/expat.h expat/lib/expat_external.h $(OUT_DIR)/include

else

.PHONY: all
all:
	mkdir -p $(OUT_DIR)/include

endif
